splitter:
    !YearSplitter
        train_len: 1
        test_len: 1
        gap: 2
        year_col: 'entry_year'
labeler:
    !GradYearLabeler
        grad_cols: ['grad_year', 'grade_12_entry_year']
        entry_col: 'entry_year'
        max_diff: 2
        withdraw_columns: ['dropout_year']
        drop_columns: ['in_state_transfer_year', 'transfer_out_year']
imputer:
    !AverageImputer
        default_method: 'median'
        col_methods: {'gpa_9': 'median'}
        regex_methods: {}
model:
    !PercentileRankOneFeature
        feature: 'gpa_9'
        descend: True
loaders:
    grade_9_gpa: {}
preprocessor: []
